spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gameBoardDev
    username: bartoszgebka
    password: admin
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate

server:
  servlet:
    context-path: /api